sudo: required
dist: trusty

language: generic

git:
  submodules: false

services:
  - docker

notifications:
  email:
    - travis@codelabs.ch

jobs:
  include:
    - stage: Build on debian and ubuntu
      script:
        - travis_wait docker pull codelabsch/muen-dev-env:debian
        - docker run codelabsch/muen-dev-env /bin/sh -c "git pull --rebase && git submodule update && make iso"
    - script:
        - travis_wait docker pull codelabsch/muen-dev-env:ubuntu
        - docker run codelabsch/muen-dev-env /bin/sh -c "git pull --rebase && git submodule update && make iso"
