sudo: required
dist: trusty
language: generic
git:
  submodules: false
services:
  - docker
notifications:
  email:
    - travis@codelabs.ch
env:
  global:
    - DOCKER_IMG=codelabsch/muen-dev-env
jobs:
  include:
    - stage: Build on debian and ubuntu
      script:
        - travis_retry docker pull $DOCKER_IMG:debian
        - docker run $DOCKER_IMG /bin/sh -c "git pull --rebase && git submodule update && make iso"
    - script:
        - travis_retry docker pull $DOCKER_IMG:ubuntu
        - docker run $DOCKER_IMG /bin/sh -c "git pull --rebase && git submodule update && make iso"
